### ISSUE TITLE
NDS: Missing keyboard.{grit, png} in repository

### ISSUE THREAD

**Issue by asiekierka** [asiekierka/atari800#1]

**Comment by Rkr77441** [comment]
Hello I was wondering how do I get it to work I did the dsp firm thing and the purple image pops up on the top screen when I open the cia version of it and it says something about the altirra Roms and something about a help file?

**Comment by asiekierka** [comment]
I do not provide support for the CIA version; it is unofficial. @RandomMan25XX

**Comment by RandomMan25XX** [comment]
> Hello I was wondering how do I get it to work I did the dsp firm thing and the purple image pops up on the top screen when I open the cia version of it and it says something about the altirra Roms and something about a help file?

Make sure you have the necessary bios files needed by the emulator as they are necessary for all versions of atari800, and make sure that any further issues you have are brought up on my repository next time if it regards the CIA builds

**Comment by asiekierka** [comment]
Note that when you start the emulator, you should press L to access the menu.

The official BIOS files should not be strictly necessary; Altirra's are a fine replacement for most games. You can (legally!) download them here, though: [xf25.zip](https://osdn.net/projects/sfnet_atari800/downloads/ROM/Original%20XL%20ROM/xf25.zip/)

**Comment by RandomMan25XX** [comment]
I wasn't fully aware what that was or that it was an option, good to know

**Comment by asiekierka** [comment]
The Altirra BIOS and OS is a replacement for the official Atari BIOS and OS, maintained by the Altirra emulator - regarded to be the best Atari 400/800/5200/XL/XE emulator by a wide margin. For some time now, atari800 has bundled a fairly recent version of the Altirra ROMs with the emulator, as it allows the emulator to work without downloading any additional BIOS files.

However, so the story goes (not legal advice): the official Atari BIOS and OS was bundled with Atari's permission with a commercial emulator named X-Former. When Atari collapsed and ended up being pushed around from owner to owner, the emulator's developer decided to make an old version of the emulator available for free, which then allowed people to download it and use the ROM files contained in it for free likewise. Notably, though, the ROMs are still property of Atari - you cannot distribute them without the emulator, the license agreement only permitted distributing them *with* the emulator, so that's how it is done.
