### ISSUE TITLE
Networking/R:

### ISSUE THREAD

**Issue by glitchphan** [asiekierka/atari800#3]
The R: device is enabled but it doesn't actually seem to use the network/wifi connection. Any chance of getting that working?

**Comment by asiekierka** [comment]
Hmm. Someone finally asked about it!

Do you have a good way to test it? I'm not versed in 8-bit Atari networking enough to figure out how it's supposed to be used :(

**Comment by glitchphan** [comment]
As far as I know atari800 only responds to two AT commands, shown in rhandler.c I think.. It will say OK to:
ATDI[space]address[space]port
then it will try to connect. The ATDI is case sensitive. BobTerm should work as a terminal program without an rhandler, if I remember correctly.

**Comment by asiekierka** [comment]
0.3.8 fixes it! Thanks for letting me know.

**Comment by glitchphan** [comment]
This is very awesome, thank you! I can finally connect out from the emulator!

One thing, however. It doesn't seem to easily come back/disconnect from the first connection. Normally with atari800 on other platforms, you will disconnect, wait about 5 seconds or so, then press enter (or maybe any key), and it will say NO CARRIER then letting you type more commands. On the 3DS, it doesn't do that and is stuck in what seems to be a "connected" state. In Bobterm, there is a hangup command that seems to somehow get it out of this state so you can type an ATDI command again, but in another terminal (Ice-T) the hangup command is probably only trying to send +++[pause]ATH0 which obviously does nothing. Bobterm sends that too, of course, but it's doing something else to reset the port or something. With any other terminal, you'd have to do a restart after each connection.
