### ISSUE TITLE
It shows up but it says something about the Altirra Rom’s and something about a help file

### ISSUE THREAD

**Issue by Rkr77441** [asiekierka/atari800#4]
Hello im using the cia version of the Atari rom an I got it to work but this purple image is on the top screen with a floppy disk going into a slot and there’s text that says something about the altirra Roms and something about a help file?

**Comment by Rkr77441** [comment]
I got into the menu but what bios do I need and I’d altirra just a bunch of roms and where do I get and or find it abd where do I put it??

**Comment by Rkr77441** [comment]
Nvm I’m not gonna download it anymore to confusing

**Comment by asiekierka** [comment]
> what bios do I need

The built-in one should be fine.
